version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: anglure_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: anglure_user
      POSTGRES_PASSWORD: anglure_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
